export const ErrorCode = {
    // General Error
    UNKNOWN: 9000,
    SYSTEM_GENERAL_ERROR: 9001,
    DATABASE_ERROR: 9002,
    INVALID_HEADERS: 9003,
    SYNTAXERROR: 9004,

    // Database
    DATABASE_CONNECTION_ERROR: 9100,
    INSERT_ERROR: 9101,
    UPDATE_ERROR: 9102,
    DELETE_ERROR: 9103,
    RECORD_NOT_FOUND: 9104,

    // Permision
    PERMISSION_DENIED: 10001,

    // Auth
    LOGIN_FAIL: 1001,
    INVALID_TOKEN: 1002,
    MISSING_JWT_AUTH: 1003,
    DELETED_ACCOUNT: 1004,
    DISABLED_ACCOUNT: 1005,
    EXPIRED_TOKEN: 1006,
    INVALID_EMAIL_ADDRESS: 1007,
    INVALID_PASSWORD: 1008,
    INVALID_FILE_FORMAT: 'INVALID_FILE_FORMAT',
    INVALID_INPUT_DATA: 'INVALID_INPUT_DATA',
    INVALID_OTP: 'INVALID_OTP',

    // File
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    FILE_NOT_FOUND: 'FILE_NOT_FOUND',

    // User = 2000
    NEW_PASSWORD_SAME_AS_CURRENT_PASSWORD: 2001,
    NON_ACTIVATED_ACCOUNT: 2002,
    OTP_LIMIT_REACHED: 2003,
    USER_NOT_FOUND: 2004,
    TOKEN_NOT_FOUND: 2005,

    // EMAIL
    TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
};
