export const ErrorMessageCode = {
    // General Error
    UNKNOWN: 'UNKNOWN',
    SYSTEM_GENERAL_ERROR: 'SYSTEM_GENERAL_ERROR',
    DATABASE_ERROR: 'DATABASE_ERROR',
    INVALID_HEADERS: 'INVALID_HEADERS',
    SYNTAX_ERROR: 'SYNTAX_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    INVALID: 'INVALID',

    // Database
    DATABASE_CONNECTION_ERROR: 'DATABASE_CONNECTION_ERROR',
    INSERT_ERROR: 'INSERT_ERROR',
    UPDATE_ERROR: 'UPDATE_ERROR',
    DELETE_ERROR: 'DELETE_ERROR',
    RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',

    // Permision 10000
    PERMISSION_DENIED: 'PERMISSION_DENIED',

    // Auth 1000
    AUTH_LOGIN_FAIL: 'AUTH_LOGIN_FAIL',
    AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
    AUTH_MISSING_JWT: 'AUTH_MISSING_JWT',
    AUTH_DELETED_ACCOUNT: 'AUTH_DELETED_ACCOUNT',
    AUTH_DISABLED_ACCOUNT: 'AUTH_DISABLED_ACCOUNT',
    AUTH_EXPIRED_TOKEN: 'AUTH_EXPIRED_TOKEN',
    AUTH_INVALID_EMAIL_ADDRESS: 'AUTH_INVALID_EMAIL_ADDRESS',
    AUTH_INVALID_PASSWORD: 'AUTH_INVALID_PASSWORD',

    // User = 2000
    NEW_PASSWORD_SAME_AS_CURRENT_PASSWORD: 'NEW_PASSWORD_SAME_AS_CURRENT_PASSWORD',
    NON_ACTIVATED_ACCOUNT: 'NON_ACTIVATED_ACCOUNT',
    OTP_LIMIT_REACHED: 'OTP_LIMIT_REACHED',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
};
