export const ErrorMessageCode = {
    // AUTH
    LOGIN_FAIL: 'LOGIN_FAIL',
    INVALID_TOKEN: 'INVALID_TOKEN',
    MISSING_JWT_AUTH: 'MISSING_JWT_AUTH',
    DELETED_ACCOUNT: 'DELETED_ACCOUNT',
    DISABLED_ACCOUNT: 'DISABLED_ACCOUNT',
    EXPIRED_TOKEN: 'EXPIRED_TOKEN',
    INVALID_EMAIL_ADDRESS: 'INVALID_EMAIL_ADDRESS',
    INVALID_INPUT_DATA: 'INVALID_INPUT_DATA',
    INVALID_OTP: 'INVALID_OTP',
    INVALID_PASSWORD: 'INVALID_PASSWORD',

    // FILE
    FILE_TOO_LARGE: 'FILE_TOO_LARGE',
    FILE_NOT_FOUND: 'FILE_NOT_FOUND',
    INVALID_FILE_FORMAT: 'INVALID_FILE_FORMAT',

    // USER
    NEW_PASSWORD_SAME_AS_CURRENT_PASSWORD: 'NEW_PASSWORD_SAME_AS_CURRENT_PASSWORD',
    NON_ACTIVATED_ACCOUNT: 'NON_ACTIVATED_ACCOUNT',
    OTP_LIMIT_REACHED: 'OTP_LIMIT_REACHED',
    TOKEN_NOT_FOUND: 'TOKEN_NOT_FOUND',
    USER_NOT_FOUND: 'USER_NOT_FOUND',

    // PERMISSION
    PERMISSION_DENIED: 'PERMISSION_DENIED',

    // EMAIL
    TEMPLATE_NOT_FOUND: 'TEMPLATE_NOT_FOUND',
};
